version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: yap56/foodgram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media

  frontend:
    env_file: .env
    image: yap56/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: yap56/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
