# Generated by Django 3.2.3 on 2023-07-31 15:05

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, validators=[recipes.validators.validate_tag_slug]),
        ),
    ]
