# Generated by Django 3.2.3 on 2023-07-31 16:40

from django.db import migrations, models
import django.db.models.deletion
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_counter', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipes')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
