# Generated by Django 3.2.3 on 2023-08-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230801_1039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountIngredient',
            new_name='IngredientInRecipe',
        ),
    ]
